//file name should be same as class name, as it is public class
//class name should start with capital letter
//every file is a class in java


public class Test { //class names must be pascal case, ex: Test, HelloWorld, etc.

    //main method, AKA the launching point of the program
    public static void main(String[] args) { 
        System.out.println("Hellooooo World!"); //semicolon is required at the end of every statement
    }
}
// javac is used to compile the java file, you need to include the .java extension when compiling
// java is used to run the java file
// 'java Test' will run the Test.java file, you don't need to include the .java extension when running
// every time you make a change to the file, you have to recompile it